### PR TITLE
Eslint updates

### PR DESCRIPTION
**Pull request by Snugug**
2.0 updates for ESLint

`DCO 1.1 Signed-off-by: Sam Richard <snugug@us.ibm.com>`

### CODE REVIEW

**Comment by Snugug** [comment]
@scottnath This should fix all of our ESLint weird things

**Comment by scottnath** [comment]
Well, well, well... look who's been a busy little open source Beaver!

**Comment by scottnath** [comment]
`This pull request can be automatically merged by project collaborators` of which `scottnath` is not...

**Comment by Snugug** [comment]
@scottnath well if you [accepted your invite](https://github.com/punchcard-cms) you could be a collaborator too!

**Comment by scottnath** [comment]
#revisionisthistory

**Pull request merged**
